env:
  es6: true
parser: '@typescript-eslint/parser'
parserOptions:
  project: './tsconfig.eslint.json'
  tsconfigRootDir: '.'
plugins:
  - '@typescript-eslint'
extends:
  - 'plugin:@typescript-eslint/recommended'
rules:
  indent: off
  '@typescript-eslint/indent':
    - warn
    - tab
  quotes: off
  '@typescript-eslint/quotes':
    - warn
    - double
  semi: off
  '@typescript-eslint/semi':
    - warn
    - always
  linebreak-style:
    - warn
    - unix
  eol-last:
    - warn
    - never

  '@typescript-eslint/consistent-type-definitions':
    - error
    - type
  '@typescript-eslint/type-annotation-spacing':
    - warn
    - before: false
      after: true
  '@typescript-eslint/member-delimiter-style':
    - error
    - multiline:
        delimiter: comma
        requireLast: false

  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/explicit-member-accessibility': off

  '@typescript-eslint/no-unused-vars':
    - warn
    - vars: all
      args: after-used
      ignoreRestSiblings: true